apiVersion: v1
kind: Secret
metadata:
  name: velero-credentials
  namespace: {{ index . "namespace" }}
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id={{ index . "AWS_ACCESS_KEY_ID" }}
    aws_secret_access_key={{ index . "AWS_SECRET_ACCESS_KEY" }}
